### ISSUE TITLE
Convert `TODO` file into GH issues

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#578]
Currently we have a `TODO` file in the top level folder but this needs to be converted into issues.

To do:
- [x] For each bullet:
	- [x] If to do relevant and not yet fixed or not sure if it has been fixed, create issue (95%)
	- [x] If sure it is not relevant or sure it was fixed, then can omit (5%)
- [x] Remove `TODO` file
