### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by danielinteractive** [Roche/crmPack#683]
To do:

Clean up in below steps by separate PRs (to avoid too large PRs).

- Please first check if a helper function is really used in the package, and whether it could be replaced by a standard function from `checkmate` etc.
- If it makes sense, please move helper functions to separate helper files such as `helpers_data.R` etc. or create a new such separate helper file. 
- Transition to snake_case and prefix internal helper function names also with `h_` to indicate that they are helper functions.
- Add tests everywhere, add examples for user facing functions

When somebody takes a task please put your name next to it (edit this description) so we don't duplicate any work :) thanks!

- [x] `matchTolerance`
- [x] `%~%` [John Kirkpatrick #688]
- [x] `noOverlap` John Kirkpatrick #694]
- [x] `is.scalar` (e.g. this one I am pretty sure we can replace by the `checkmate` function `test_scalar()`) [John Kirkpatrick #686]
- [x] `is.bool` (-> `test_flag()`) [John Kirkpatrick #686]
- [x] `is.wholenumber` (`-> `test_number()`) [John Kirkpatrick #693]
- [x] `safeInteger` [John Kirkpatrick #693]
- [x] `is.probability` (remove because we have already https://github.com/Roche/crmPack/blob/main/R/checkmate.R#L117) 
          [**Dimitris** #692]
- [x] `is.range` (remove I guess) 
          [**Dimitris** #692]
- [x] `is.probRange` (remove because we have already https://github.com/Roche/crmPack/blob/main/R/checkmate.R#L159)
          [**Dimitris** #692]
- [x] `logit` and `probit`[Nothing to do: see discussion below.]
- [x] `crmPackExample` and `crmPackHelp` -> this is a user facing function, so no `h_` prefix here [Nothing to do here.  See below.]
- [x] `plot.gtable` and `print.gtable` -> needed? [John Kirkpatrick #696]
- [x] `dinvGamma`, `pinvGamma`, `qinvGamma`, `rinvGamma` -> replace by using other package's function? [No action: see below]
- [x] `myBarplot`
- [x] `multiplot` [John Kirkpatrick #699]

**Comment by Puzzled-Face** [comment]
`%~%`  appears to be used only in the example documenting the function...

**Comment by Puzzled-Face** [comment]
`multiplot` appears only to be used in `design/devel/rolling-crm-Simona.Rmd` and its functionality exists in other packages, such as `cowplot` and `ggpubr`.  Suggest removal.

As this is an exported function, add a note to `NEWS`.

**Comment by Puzzled-Face** [comment]
`myBarplot` is called several times in `simulations/methods.R`, but nowhere else.  Therefore, suggest
- Rename to `barplot_percentages`
- Move from helpers.R to (new file) `helpers-simulations.R`
- Create tests using `vdiffr::expect_doppelganger` to confirm unaltered performance
- Correct example code, which currently errors, to include `description` parameter

**Comment by Puzzled-Face** [comment]
Implementations of `dinvGamma` exist in two other packages that I have found:

- Package `MCMCpack` v0.4-5 last updated on 17Nov2003.
- Package EDISON v1.1.1 last updated 7 years ago.  There have been two updates since first release, both related to bugs in functions related to the inverse gamma.  EDISON appears to be a relatively large package in an unrelated field.

Suggest retaining `crmPack`'s implementations of `<x>invgamma` functions.

**Comment by Puzzled-Face** [comment]
I found no instances of `h_crmPackExample` or `h_crmPackHelp`.  What is required here?

**Comment by Puzzled-Face** [comment]
`logit` and `probit`: do you want these replaced with `stats::qlogis` and `stats::qnorm` respectively?

**Comment by Puzzled-Face** [comment]
Replace `matchTolerance(x, table)` with `assert_integerish(x - table, lower =0, upper = 0, tol = 1e-10)`?

**Comment by danielinteractive** [comment]
> Replace `matchTolerance(x, table)` with `assert_integerish(x - table, lower =0, upper = 0, tol = 1e-

I guess we could use `assert_equal` if that exists or something similar from `checkmate`?

**Comment by danielinteractive** [comment]
> `logit` and `probit`: do you want these replaced with `stats::qlogis` and `stats::qnorm` respectively?

Yeah we can do that

**Comment by danielinteractive** [comment]
> I found no instances of `h_crmPackExample` or `h_crmPackHelp`.  What is required here?

Just usual cleanup here, sorry I was not precise about the task - they don't yet have a prefix and they should stay like that. That is what I meant to say 😄

**Comment by Puzzled-Face** [comment]
> > Replace `matchTolerance(x, table)` with `assert_integerish(x - table, lower =0, upper = 0, tol = 1e-
> 
> I guess we could use `assert_equal` if that exists or something similar from `checkmate`?

`checkmate does not have `xxxx_equal` or `xxxx_identical` functions.  The closest it does have is `xxxx_true`.  So we could

1. Write our own `checkmate` extension and add it to `R/checkmate.R`
2. Use `assert_integerish(x - table, lower =0, upper = 0, tol = 1e-10)`
3. Use `assert_true(x - table < 1e-10)`

2 is ugly.  3 is minimal effort, but slightly opaque.  I prefer 1: it's little effort (essentially wrapping option 3 in a function), allows the tolerance to be changed when required and most clearly reflects the intent of the code.

What to call the wrapper function?
- `assert_equal`
- `assert_equal_wth_tolerance`
- Something else

Should we create the full set of `checkmate`-like functions (ie `check_xxxx`, `test_xxxx`, `assertXxxx` etc) or just the one that we need?

Once we are happy, consider submitting to `checkmate`?

**Comment by Puzzled-Face** [comment]
> `logit` and `probit`: do you want these replaced with `stats::qlogis` and `stats::qnorm` respectively?

We may have a problem here. `logit` and `probit` appear in the body of `datamodel` slot functions for (eg) `LogisticLogNormal` and `ProbitLogNormal`.  The code in this slot needs to be both valid R code and valid JAGS code.  `stats::plogis`, for example, is not valid JAGS code. 

I don't think the `%_%` pipe operator will be helpful here.

Advice please.

**Comment by danielinteractive** [comment]
> What to call the wrapper function?
> 
> * `assert_equal`
> * `assert_equal_wth_tolerance`
> * Something else
> 

I think `assert_equal` is good because it parallels `expect_equal` from `testthat`

> Should we create the full set of `checkmate`-like functions (ie `check_xxxx`, `test_xxxx`, `assertXxxx` etc) or just the one that we need?

Maybe not `expect_equal` since that is provided by `testthat` but the other 3 yes

> Once we are happy, consider submitting to `checkmate`?

Yeah I submitted an idea one time to them but they were not really open to it. Therefore I would not think about this for now (and we have an idea open for Stats Eng in general to make a checkmate extension package taking things from across our packages into there)

**Comment by danielinteractive** [comment]
> > `logit` and `probit`: do you want these replaced with `stats::qlogis` and `stats::qnorm` respectively?
> 
> We may have a problem here. `logit` and `probit` appear in the body of `datamodel` slot functions for (eg) `LogisticLogNormal` and `ProbitLogNormal`. The code in this slot needs to be both valid R code and valid JAGS code. `stats::plogis`, for example, is not valid JAGS code.
> 
> I don't think the `%_%` pipe operator will be helpful here.
> 
> Advice please.

Ah ok ... yeah then let's keep them and just add tests vs. the `stats` functions.
